version: "3.7"
services:
  soda-core-postgres:
    image: soda-demo-data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=soda
      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
